name: Windows QT Build

# on:
#  push:
#    tags:
#      - 'v*'
on:
  push:
    branches: [ "cicd-pipeline" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install pkg-config
      run: choco install pkgconfiglite

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        aqtversion: '==3.1.*'
        version: '6.8.3'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw'
        modules: 'qtshadertools'
        tools: 'tools_mingw1310'
        cache: true

    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
    
    - name: Build
      run: |
        cd build
        mingw32-make
    
    - name: Deploy
      run: |
        cd build
        windeployqt sang-box.exe
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          build/sang-box.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}